feat: based on official workflow, add VPN/NAS packages for rk3588 docker

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,9 +2,8 @@ name: Build FriendlyWrt
 
 on:
   workflow_dispatch:
-  push:
-    tags:
-      - 'v*'
+  watch:
+    types: started
 
 permissions:
   contents: write
@@ -12,6 +11,7 @@ permissions:
 jobs:
   prepare_release:
     runs-on: ubuntu-22.04
+    if: github.event.repository.owner.id == github.event.sender.id
     steps:
     - name: Get release tag
       id: release_tag
@@ -35,6 +35,7 @@ jobs:
   build_friendlywrt:
     needs: prepare_release
     runs-on: ubuntu-22.04
+    if: github.event.repository.owner.id == github.event.sender.id
     strategy:
       matrix:
         VERSION: ['25.12']
@@ -146,13 +147,6 @@ jobs:
         TARGET_IMAGE_DIRNAME=${DIST_DIR}
         TARGET_FRIENDLYWRT_CONFIG=${CONFIG}
         EOL
-
-        # Fix kernel config for Docker IPVS
-        source .current_config.mk
-        KCFG=kernel/arch/arm64/configs/$(awk '{print $1}' <<< "$TARGET_KERNEL_CONFIG")
-        echo "CONFIG_IP_VS_FTP=m" >> "$KCFG"
-        echo "CONFIG_NF_NAT_FTP=m" >> "$KCFG"
-
         DEBUG_DOT_CONFIG=1 ./build.sh friendlywrt
 
     - name: Download package
@@ -163,9 +157,20 @@ jobs:
         find dl -size -1024c -exec rm -f {} \;
 
     - name: Compile friendlyWrt
+      id: compile
+      continue-on-error: true
       run: |
         cd project/friendlywrt
-        make -j$(nproc) || make -j1 V=s
+        if ! make -j$(nproc); then
+          echo "::warning::parallel build failed, retrying with V=s"
+          make -j1 V=s
+        fi
+
+    - name: Check the result and try again
+      if: steps.compile.outcome == 'failure'
+      run: |
+        cd project/friendlywrt
+        make -j1 V=s
 
     - name: Create rootfs package
       id: create_rootfs_package
@@ -190,6 +195,7 @@ jobs:
   build_img:
     needs: [prepare_release,build_friendlywrt]
     runs-on: ubuntu-22.04
+    if: github.event.repository.owner.id == github.event.sender.id
 
     strategy:
       matrix:
@@ -251,8 +257,12 @@ jobs:
       id: config
       run: |
         cd project
-        MODEL=T6-R6S-R6C-M6-Series
-        SUFFIX="-docker"
+        case ${{ matrix.CPU }} in
+        rk3588)
+          MODEL=T6-R6S-R6C-M6-Series
+          ;;
+        esac
+        [ "${{ matrix.SET }}" == "docker" ] && SUFFIX="-docker"
         IMG_FILE=${MODEL}-FriendlyWrt-${{ matrix.VERSION }}${SUFFIX}.img
         TGZ_FILE=images-${MODEL}-FriendlyWrt-${{ matrix.VERSION }}${SUFFIX}.tgz
         DIST_DIR=friendlywrt$(echo ${{ matrix.VERSION }}|awk -F . '{print $1}')${SUFFIX}
@@ -270,12 +280,6 @@ jobs:
         echo "dist_dir=$DIST_DIR" >> $GITHUB_OUTPUT
         echo "suffix=$SUFFIX" >> $GITHUB_OUTPUT
 
-        # Fix kernel config for Docker IPVS
-        source .current_config.mk
-        KCFG=kernel/arch/arm64/configs/$(awk '{print $1}' <<< "$TARGET_KERNEL_CONFIG")
-        echo "CONFIG_IP_VS_FTP=m" >> "$KCFG"
-        echo "CONFIG_NF_NAT_FTP=m" >> "$KCFG"
-
     - name: Unpack friendlywrt rootfs
       run: |
         cd project
@@ -285,6 +289,9 @@ jobs:
     - name: Compile uboot and kernel
       run: |
         cd project
+        ## If you need to modify the kernel configuration, please edit the script below
+        # source ../scripts/custome_kernel_config.sh
+
         ./build.sh uboot
         ./build.sh kernel
 
@@ -332,6 +339,7 @@ jobs:
   cleanup_intermediate_assets:
     needs: [prepare_release, build_img]
     runs-on: ubuntu-22.04
+    if: github.event.repository.owner.id == github.event.sender.id
     steps:
     - name: Delete intermediate assets from release
       env:
